### ISSUE TITLE
Max retries exceeded with url: /api/v1/targets 

### ISSUE THREAD

**Issue by wgitewolf** [danialhalo/AcuAutomate#1]
I followed all installation steps > Now I am getting this error after running cmd
 ` python3 AcuAutomate.py scan -d https://www.google.com`

```
[*] Running scan on : https://www.google.com
HTTPSConnectionPool(host='localhost', port=3443): Max retries exceeded with url: /api/v1/targets (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa4ff291e10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Traceback (most recent call last):
  File "/home/krishna/.local/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/krishna/.local/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/krishna/.local/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/krishna/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/home/krishna/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/home/krishna/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/home/krishna/.local/lib/python3.10/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/home/krishna/.local/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fa4ff291660>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

```

**Comment by wgitewolf** [comment]
<img width="1261" alt="1" src="https://github.com/danialhalo/AcuAutomate/assets/76523967/44786975-a791-4fc6-bae4-93a3f1e73515">
<img width="1256" alt="2" src="https://github.com/danialhalo/AcuAutomate/assets/76523967/59bec1a1-6645-47e1-9ec8-4402f0aa8052">

**Comment by danialhalo** [comment]
Hi Thanks for reaching out, I would more helpful if you could share your config.json file.

**Comment by wgitewolf** [comment]
Sure here it is ,
<img width="715" alt="1" src="https://github.com/danialhalo/AcuAutomate/assets/76523967/715b5f42-d64d-44f2-b146-9b0e4ae26ed4">

**Comment by danialhalo** [comment]
Please make sure the the host-name port and scheme in the config file is same as your acunetix configuration. The Connection refused error indicates that it not able to communicate with the acunetix service

**Comment by mysk4r** [comment]
how to get the api key?

**Comment by danialhalo** [comment]
Open your acunetix and go to profiles you will find the option for generating new api key
